# Generated by Django 4.1 on 2022-08-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_firs_name_user_first_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='cars',
            field=models.ManyToManyField(to='users.car', verbose_name="user's car"),
        ),
    ]
