# Generated by Django 4.1 on 2022-08-08 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_car_user_cars'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['rating'], 'verbose_name': 'The Website', 'verbose_name_plural': 'The Websites'},
        ),
    ]
